### ISSUE TITLE
Crash when viewing text file containing special characters

### ISSUE THREAD

**Issue by cviorel** [Alexey-T/CudaLister#74] opened 2021-12-02 15:47 UTC
Viewing a text file that contains special characters, causes a crash:
`
HumanReadable,Kaomoji,KaomojiEscaped
Shruggie,"¯\_(ツ)_/¯","¯\\\_(ツ)_/¯"
TableFlip,"(╯°□°）╯︵ ┻━┻","(╯°□°）╯︵ ┻━┻"
TableDown,"┬─┬ノ( º _ ºノ)","┬─┬ノ( º _ ºノ)"
Angry,"(/ﾟДﾟ)/","(/ﾟДﾟ)/"
Disappointed,"ಠ_ಠ","ಠ_ಠ"
Strut,"ᕕ( ᐛ )ᕗ","ᕕ( ᐛ )ᕗ"
`

![image](https://user-images.githubusercontent.com/125662/144454171-9371c05a-9504-4bf2-865f-867ee196cabf.png)

OS: 

- Win 10 Pro

Versions:

- CudaLister 1.7.0
- Total Commander Version 10.00 64 bit (2021-06-10)

**Comment by Alexey-T** [comment] 2021-12-02 16:13
I cannot repeat it on 1.7.0 (released in the Github Releases page, it has 'read only' menu item disabled). file is opened ok.

**Comment by ThomasHeinrichSchmidt** [comment] 2022-02-02 12:20
I am having the same issue, on 32-bit TC 10.00 (2021-06-10) same error message, Win 10 Version 21H1 (Build 19043).
But - it is not happening all the time for the same file. Sometimes, especially shortly after the start of TC, some file opens just fine in CudaLister. But after some work, opening some other files in between, suddenly when viewing the file the issue appears. 
I had the same thing happening in previous version 1.6.21, but with 1.7 the crash now also terminates TC, before I could continue working with TC. 
I prepared a file where I was able to observe the issue quite often, see attached
[BadFile.txt](https://github.com/Alexey-T/CudaLister/files/7986303/BadFile.txt)

**Comment by Alexey-T** [comment] 2022-02-06 16:34
maybe you can give me the file (small). so I can open this file. 
and see the crash?
cannot repro it.

**Comment by ThomasHeinrichSchmidt** [comment] 2022-02-06 16:44
Yes, it's not easy to reproduce the crash. When I download [BadFile.txt](https://github.com/Alexey-T/CudaLister/files/7986303/BadFile.txt) I can also view it okay for the first couple of times. But after a while doing some work, opening some other files in between, suddenly the issue appears. Sorry I cannot relate this surely to something special I'm doing.

**Comment by ThomasHeinrichSchmidt** [comment] 2022-02-07 17:56
Maybe I found a way to reproduce. View [BadFile.txt](https://github.com/Alexey-T/CudaLister/files/7986303/BadFile.txt) first, close it, then view [BadFile2.md](https://github.com/Alexey-T/CudaLister/files/8017563/BadFile2.md), then Cudalister crashes. Sometimes it also "works" the other way round, view BadFile2.md first, close, then view BadFile.txt, crash.

**Comment by Alexey-T** [comment] 2022-02-22 18:05
yes, I see the crash now. thanks.

**Comment by Alexey-T** [comment] 2022-02-22 18:28
fixed.

**Closed by Alexey-T** 2022-02-22 18:28 UTC
Labels: bug

**Comment by ThomasHeinrichSchmidt** [comment] 2022-02-22 19:27
Thanks, let's see.

**Comment by ThomasHeinrichSchmidt** [comment] 2022-02-25 13:50
Now, after intensively using version 1.7.2 for some time now I can confirm that the error has been fixed.
Thank you!
![ThumbsUp](https://user-images.githubusercontent.com/8068047/155726467-4f5a137c-2b1a-4350-9438-aa2faae97a3e.png)

**Comment by ThomasHeinrichSchmidt** [comment] 2022-03-31 16:19
I was too optimistic, I actually experienced quite a few more crashes.
But since I installed [1.7.5.2](https://github.com/Alexey-T/CudaLister/releases/tag/1.7.5.2) I haven't had a single crash. 
That seems to have finally fixed the problem.

**Comment by Alexey-T** [comment] 2022-03-31 17:07
@ThomasHeinrichSchmidt I put the new release 1.7.5.3 with additional stability fixes in EControl

**Comment by ThomasHeinrichSchmidt** [comment] 2022-04-01 09:20
I'll give it a try, now using it for an hour, no crashes so far.
